version: '3'

networks:
  vk-network:
    driver: bridge

services:

        vk:
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - vk-network
            volumes:
                - ./../vk:/vk:rw,cached
                - vk_log:/vk/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - mariadb

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "80:80"
                - "443:443"
            networks:
                - vk-network
            depends_on:
                - vk
            volumes:
                - ./../vk/public:/vk/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            ports:
                - "6379:6379"
            networks:
                - vk-network

        memcached:
            container_name: memcached
            image: memcached:latest
            ports:
                    - "11211:11211"
            networks:
                - vk-network

        mariadb:
            container_name: mariadb
            image: mariadb:latest
            env_file:
                - ./maria/master/.env.master
            ports:
                - "3306:3306"
            volumes:
                - ./maria/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network

        percona:
            container_name: percona
            image: percona:5.7
            env_file:
                - ./percona/master/.env.master
            ports:
                - "3307:3306"
#            volumes:
#                - ./percona/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network

volumes:
    nginx_log:
    vk_log:
    db:
        driver: local
